name: 522-dockerlock
channels:
- conda-forge
dependencies:
- altair
- conda-lock=>3.0.4
- jupyterlab=4.5.0
- pandas=2.3.3
- pandera
- pip
- pointblank
- python>=3.11
- pip:
  - deepchecks
  - vegafusion